version: "3.9"
services:
  worker:
    build: .
    dockerfile: Dockerfile
    environment:
    - API_ID=11042778
    - API_HASH=583227ff3ba18dcd47f89b92fa01e092
    - BOT_TOKEN=5062201942:AAFqRnF6fxMJfTOHpr7LstDYU2WskY9ug1w
    - SESSION_STRING=BAAO0dAjZqNnl9xSI-rlvx3fds1tpJBFWngROV67eA44KRC0Xy9SMOq_yhM-4UnPdyHxlx2PvJB5xGN0yNyAVkyy_nHt7svKWPIo76IPC2C6u5jcE0DpNgyU7cua5KUDTyU64HR6byqRLmFuyxMZEJSuiD91aytbRnrWgChrRmtIORmL-OW27B22cJr8JStFCujk01Ga2ouPOP1eBbLAWXU4cxQuAT9Q-98DIETUgEIWwzTHpq0QxGZBrCJOeROdqbYVnodkjuf5u37UX6uabrFTGgcMk0EYK7RbeG_7MM_7Dq0ysm6zaU9F9b3mRU3xuxPZ442hfR_Jx5ZTKi38UV_3AAAAAHiWePgA
    - CHAT=-1001599715690
    - ADMINS=1203688744
    - LOG_GROUP=-1001799098069
    - STARTUP_STREAM=False
    - DATABASE_URI=mongodb+srv://gapemoonub:gapemoonub@cluster0.ss4bq.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
    - ADMIN_ONLY=True
    - REPLY_MESSAGE=El-enLiL
    - TIME_ZONE=Asia/Tehran
    - IS_LOOP=True
    - DELAY=5
    - QUALITY=low
    command: python3 ~/vcplayerbot/main.py
