version: "3.9"
services:
  worker:
    build: .
    environment:
      API_ID: $API_ID
      API_HASH: $API_HASH
      BOT_TOKEN: $BOT_TOKEN
      SESSION_STRING: $SESSION_STRING
      CHAT: $CHAT
      ADMINS: $ADMINS
      LOG_GROUP: $LOG_GROUP
      STARTUP_STREAM: $STARTUP_STREAM
      DATABASE_URI: $DATABASE_URI
      ADMIN_ONLY: $ADMIN_ONLY
      REPLY_MESSAGE: $REPLY_MESSAGE
      TIME_ZONE: $TIME_ZONE
      IS_LOOP: $IS_LOOP
      DELAY: $DELAY
      QUALITY: $QUALITY
      HEROKU_API_KEY: $HEROKU_API_KEY
      HEROKU_APP_NAME: $HEROKU_APP_NAME
